In [ ]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns
from scipy import stats
from sklearn.compose import ColumnTransformer
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder, StandardScaler

plt.rcParams["figure.figsize"] = (8, 4)

url = "https://www.datos.gov.co/resource/gt2j-8ykr.json?$limit=10000"
df = pd.read_json(url)

In [ ]:
df.head()

,fecha_reporte_web,id_de_caso,fecha_de_notificaci_n,departamento,departamento_nom,ciudad_municipio,ciudad_municipio_nom,edad,unidad_medida,sexo,...,recuperado,fecha_inicio_sintomas,fecha_diagnostico,fecha_recuperado,tipo_recuperacion,per_etn_,fecha_muerte,nom_grupo_,pais_viajo_1_cod,pais_viajo_1_nom
0,2020-12-24 00:00:00,1556979,2020-12-22 00:00:00,76,VALLE,76001,CALI,67,1,F,...,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN,NaN,NaN
1,2020-12-24 00:00:00,1556980,2020-12-19 00:00:00,76,VALLE,76001,CALI,66,1,F,...,Recuperado,2020-12-07 00:00:00,2020-12-23 00:00:00,2020-12-25 00:00:00,Tiempo,6,NaN,NaN,NaN,NaN
2,2020-12-24 00:00:00,1556981,2020-12-19 00:00:00,76,VALLE,76001,CALI,68,1,F,...,Recuperado,2020-12-18 00:00:00,2020-12-22 00:00:00,2021-01-01 00:00:00,Tiempo,6,NaN,NaN,NaN,NaN
3,2020-12-24 00:00:00,1556982,2020-12-22 00:00:00,76,VALLE,76001,CALI,74,1,F,...,Fallecido,2020-12-17 00:00:00,2020-12-23 00:00:00,NaN,NaN,6,2020-12-30 00:00:00,NaN,NaN,NaN
4,2020-12-24 00:00:00,1556983,2020-12-22 00:00:00,76,VALLE,76001,CALI,65,1,F,...,Recuperado,2020-12-21 00:00:00,2020-12-23 00:00:00,2021-01-04 00:00:00,Tiempo,6,NaN,NaN,NaN,NaN

In [ ]:
df.shape

(10000, 23)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   fecha_reporte_web      1000 non-null   object
 1   id_de_caso             1000 non-null   int64
 2   fecha_de_notificaci_n  1000 non-null   object
 3   departamento           1000 non-null   int64
 4   departamento_nom       1000 non-null   object
 5   ciudad_municipio       1000 non-null   int64
 6   ciudad_municipio_nom   1000 non-null   object
 7   edad                   1000 non-null   int64
 8   unidad_medida          1000 non-null   int64
 9   sexo                   1000 non-null   object
 10  fuente_tipo_contagio   1000 non-null   object
 11  ubicacion              1000 non-null   object
 12  estado                 1000 non-null   object
 13  recuperado             1000 non-null   object
 14  fecha_inicio_sintomas  985 non-null    object
 15  fecha_diagnostico      1000 non-null   object
 16  fecha_recuperado       961 non-null    object
 17  tipo_recuperacion      961 non-null    object
 18  per_etn_               1000 non-null   int64
 19  fecha_muerte           41 non-null     object
 20  nom_grupo_             13 non-null     object
dtypes: int64(6), object(15)
memory usage: 164.2+ KB

In [ ]:
df.describe()

,id_de_caso,departamento,ciudad_municipio,edad,unidad_medida,per_etn_,pais_viajo_1_cod
count,1.000000e+04,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,2.0
mean,9.603816e+05,1065.624100,30924.758200,40.31960,1.003900,5.882200,484.0
std,6.211799e+05,5089.771377,27285.335811,17.68062,0.066972,0.615598,0.0
min,1.861700e+04,5.000000,5001.000000,1.00000,1.000000,1.000000,484.0
25%,4.754108e+05,11.000000,11001.000000,27.00000,1.000000,6.000000,484.0
50%,9.912775e+05,20.000000,15001.000000,37.00000,1.000000,6.000000,484.0
75%,1.408394e+06,68.000000,54405.000000,52.00000,1.000000,6.000000,484.0
max,5.764914e+06,47001.000000,99001.000000,107.00000,3.000000,6.000000,484.0